name: 每日清空 R2 存储桶 linkmeapk

on:
  schedule:
    # 每天 UTC 0 点（北京时间 8 点）执行，如需北京时间 0 点改为 '0 16 * * *'
    - cron: '30 0 * * *'
  workflow_dispatch: # 允许手动触发测试
jobs:
  clear-r2:
    runs-on: ubuntu-latest
    steps:
      - name: 配置aws
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set region auto
      - name: 清空所有文件
        run: |
          aws s3 rm s3://${{ secrets.R2_BUCKET_NAME }}/ --recursive --endpoint-url ${{ secrets.R2_ENDPOINT }} --region auto
      - name: 发送邮件
        uses: dawidd6/action-send-mail@v6
        with:
            server_address: ${{ secrets.EMAIL_STMP }}
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASS_CODE }}
            subject: ✅ R2存储清除通知，删除所有apk文件
            to: ${{ secrets.SEND_PERSONS }}
            from: LinkMe build actions
            body: |
              你好，LinkMe的仓库贡献者
              ✅ 所有之前R2构建的APK已经被清空
              ✅ 释放空间成功！
              😊 祝你新的一天生活愉快！
        
